// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace sovosweather.Migrations
{
    [DbContext(typeof(WeatherContext))]
    partial class WeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("Models.CityAveragedWeatherData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AverageHighTemp");

                    b.Property<decimal>("AverageLowTemp");

                    b.Property<string>("City");

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("State");

                    b.HasKey("ID");

                    b.ToTable("AveragedDatum");
                });

            modelBuilder.Entity("Models.WeatherData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<DateTime>("Date");

                    b.Property<decimal>("HighTemp");

                    b.Property<decimal>("LowTemp");

                    b.Property<string>("State");

                    b.HasKey("ID");

                    b.ToTable("WeatherDatum");
                });
#pragma warning restore 612, 618
        }
    }
}
